# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-18 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='search',
            new_name='s',
        ),
    ]
